version: "3.5"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: faithpoint-prod
    environment:
      - POSTGRES_USER=faithpoint
      - POSTGRES_PASSWORD=faithpoint
      - POSTGRES_DB=faithpoint_prod
      - POSTGRES_HOST=faithpoint-db
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    networks:
      - faithpoint-network
    depends_on:
      - faithpoint-db

  faithpoint-db:
    image: postgres:13.3-alpine
    container_name: faithpoint-db
    environment:
      - POSTGRES_USER=faithpoint
      - POSTGRES_PASSWORD=faithpoint
      - POSTGRES_DB=faithpoint_prod
    volumes:
      - faithpoint-db-data:/var/lib/postgresql/data
    networks:
      - faithpoint-network

volumes:
  faithpoint-db-data:

networks:
  faithpoint-network:
