name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --force

      - name: Build the application
        run: npm run build

      - name: Build Docker image
        run: |
          npm install --save-dev @babel/cli @babel/core @babel/preset-env @babel/preset-typescript
          npx babel src --extensions \".js,.ts\" --out-dir dist --copy-files

      - name: Copy Docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_PUBLIC_IP }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: .
          target: /path/to/app

      - name: Deploy Docker image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_PUBLIC_IP }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /path/to/app
            docker-compose down
            docker-compose up -d
